### ISSUE TITLE
Curly brackets inside strings shown as error

### ISSUE THREAD

**Issue by daredloco** [MattA-Official/tyd-lang#24]
**Describe the bug**
Curly brackets inside a string will result in an exception

**To Reproduce**
1. Write curly brackets inside strings (eg. SomeValue "Hello {World}")

**Expected behavior**
Not showing an exception

**Screenshots**
![screen](https://user-images.githubusercontent.com/60240491/87568345-e4dada80-c69b-11ea-9260-5b04110bcf84.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - VScode Version [e.g. 1.47.0]
 - Extension Version [e.g. 1.2.1]

**Comment by MattA-Official** [comment]
Hopefully, this can be fixed for the next update. In the meantime, you can disable the extension until tomorrow when the update should be released.

**Comment by ghost** [comment]
This will be fixed in 1.2.1

Locking for now as 1.2.1 will probably release tonight (GMT).
